export const FEATURE_ICONS: Record<string, string> = {
  'auth': '🔐',
  'payments': '💳',
  'file-uploads': '📁',
  'email': '✉️',
  'realtime': '⚡',
  'search': '🔍',
  'background-jobs': '⚙️',
  'push-notifications': '🔔',
  'analytics': '📊',
  'data-export': '📤',
  'feature-flags': '🚩',
  'ai': '🤖',
  'cms': '📝',
  'monitoring': '🩺',
  'comments': '💬',
  'support': '🎧',
  'crm': '🤝',
};
